### PR TITLE
upgrade CI to Python 3.11

### PR DESCRIPTION
**Pull request by kr-stn**
Add latest Python release 3.11 to CI testing and latest testing targets in the workflows.

https://docs.python.org/3.11/whatsnew/3.11.html

### CODE REVIEW

**Comment by kr-stn** [comment]
It appears 3.11 is working fine, except on Window where the 3.11 compatible `fiona` packages are not resolvable yet.

`fiona` itself is 3.11 compatible: https://github.com/Toblerity/Fiona/issues/1087

As soon as the py311 packages are available on conda-forge we should be able to test and merge this to completion. I propose to keep this PR open as a reminder to re-test when the package is available.

```
UnsatisfiableError: The following specifications were found
This can take several minutes.  Press CTRL-C to abort.
failed
to be incompatible with the existing python installation in your environment:

Specifications:

  - fiona -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*']

Your python: python=3.11

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package pypy3.8 conflicts for:
pyyaml -> python[version='>=3.8,<3.9.0a0'] -> pypy3.8[version='7.3.*|7.3.8.*|7.3.9.*']
pyyaml -> pypy3.8[version='>=7.3.8|>=7.3.9']

Package expat conflicts for:
fiona -> libgdal[version='>=3.5.2,<3.6.0a0'] -> expat[version='>=2.2.10,<3.0.0a0|>=2.2.10,<3.0a0|>=2.4.2,<3.0a0|>=2.4.3,<3.0a0|>=2.4.4,<3.0a0|>=2.4.6,<3.0a0|>=2.4.7,<3.0a0|>=2.4.8,<3.0a0|>=2.4.9,<3.0a0|>=2.4.1,<3.0a0|>=2.3.0,<3.0a0|>=2.3.0,<3.0.0a0|>=2.2.9,<3.0.0a0|>=2.2.5,<3.0.0a0|>=2.2.5,<3.0a0']
pyyaml -> pypy3.9[version='>=7.3.9'] -> expat[version='>=2.4.1,<3.0a0|>=2.4.7,<3.0a0|>=2.4.8,<3.0a0|>=2.4.9,<3.0a0|>=2.5.0,<3.0a0']
shapely -> pypy3.9[version='>=7.3.9'] -> expat[version='>=2.4.1,<3.0a0|>=2.4.8,<3.0a0|>=2.4.9,<3.0a0|>=2.5.0,<3.0a0']

Package packaging conflicts for:
pip -> wheel -> packaging[version='>=20.2']
pip -> packaging

Package pypy3.7 conflicts for:
pyyaml -> pypy3.7[version='>=7.3.5|>=7.3.7']
pyyaml -> python[version='>=3.7,<3.8.0a0'] -> pypy3.7[version='7.3.*|7.3.5.*|7.3.7.*']

Package python_abi conflicts for:
fiona -> click[version='>=4.0'] -> python_abi[version='2.7.*|3.11.*|3.8|3.9|3.7',build='*_cp27m|*_pypy39_pp73|*_cp311|*_pypy38_pp73|*_pypy37_pp73']
pip -> python[version='>=3.7'] -> python_abi[version='2.7.*|3.10.*|3.7.*|3.7|3.8|3.9|3.9.*|3.8.*|3.11.*|3.6.*',build='*_cp27m|*_cp311|*_cp38|*_cp39|*_cp310|*_pypy39_pp73|*_pypy38_pp73|*_pypy37_pp73|*_cp37m|*_cp36m']
shapely -> python_abi[version='3.10.*|3.9|3.9.*|3.11.*|3.8.*|3.8|3.7.*|3.7|3.6.*',build='*_pypy37_pp73|*_cp37m|*_pypy38_pp73|*_cp38|*_cp311|*_cp310|*_pypy39_pp73|*_cp39|*_cp36m']
pyyaml -> python_abi[version='2.7.*|3.10.*|3.9.*|3.8.*|3.9|3.8|3.11.*|3.7.*|3.7|3.6.*',build='*_cp27m|*_cp311|*_pypy38_pp73|*_pypy39_pp73|*_cp310|*_cp39|*_cp38|*_cp37m|*_pypy37_pp73|*_cp36m']
fiona -> python_abi[version='3.10.*|3.8.*|3.9.*|3.7.*|3.6.*',build='*_cp37m|*_cp39|*_cp38|*_cp310|*_cp36m']

Package colorama conflicts for:
pip -> colorama
fiona -> click[version='>=4.0'] -> colorama
python=3.11 -> pip -> colorama

Package distlib conflicts for:
python=3.11 -> pip -> distlib
pip -> distlib

Package ucrt conflicts for:
python=3.11 -> libzlib[version='>=1.2.13,<1.3.0a0'] -> ucrt[version='>=10.0.20348.0']
fiona -> ucrt[version='>=10.0.20348.0']
shapely -> ucrt[version='>=10.0.20348.0']
pyyaml -> ucrt[version='>=10.0.20348.0']

Package setuptools conflicts for:
fiona -> munch -> setuptools[version='>=17.1']
pyyaml -> cython -> setuptools
pip -> setuptools
fiona -> setuptools
python=3.11 -> pip -> setuptools

Package wincertstore conflicts for:
pip -> setuptools -> wincertstore[version='>=0.2']
fiona -> setuptools -> wincertstore[version='>=0.2']

Package pypy3.9 conflicts for:
pyyaml -> pypy3.9[version='>=7.3.8|>=7.3.9']
pyyaml -> python[version='>=3.9,<3.10.0a0'] -> pypy3.9[version='7.3.*|7.3.8.*|7.3.9.*']The following specifications were found to be incompatible with your system:

  - feature:/win-[64](https://github.com/sentinelsat/sentinelsat/actions/runs/3354810352/jobs/5562699251#step:5:65)::__win==0=0
  - feature:|@/win-64::__win==0=0
  - fiona -> click[version='>=4.0'] -> __unix
  - fiona -> click[version='>=4.0'] -> __win
```

**Comment by kr-stn** [comment]
Good news is - Python 3.11 is fine to use for everyone not on Windows 1 day after release! 🥳

**Review by j08lue — APPROVED** [review]
Great! Should we merge this now or wait until 3.11 works on Windows, too (i.e. Fiona is available)? Or keep Windows at 3.10 for now and make a ticket for bumping that later?

**Comment by kr-stn** [comment]
@j08lue or we just wait less than 24 hours until the package is available in conda-forge and we have full Python 3.11 support :) 

Merging this now.

**Pull request merged**
