### PR TITLE
Suggestion for #124: custom logo for sentinelsat

### PR DESCRIPTION
**Pull request by yepremyana**
includes 
- black/white image svg, png
- colored image svg, png

Hope you all like it! :)

suggestion for #124

### CODE REVIEW

**Comment by valgur** [comment]
That's really nice and unexpected. Thank you! I think it looks great. 
Did you draw it yourself or is it from somewhere else? Would like to credit it accordingly.
Need to think of a good way to include it in the readme.

**Comment by yepremyana** [comment]
@valgur @Fernerkundung Thank you! I designed it in illustrator.

**Comment by j08lue** [comment]
Pretty nice, thanks @yepremyana. Could you make the swath a bit narrower and in a color that stands out more than the light grey? On first sight, it looked like a pacman-like smiley to me, because the swath looks like cut out from the marble...

**Comment by j08lue** [comment]
We don't have to be extremely accurate about this, but none of the Sentinels has a parabolic antenna pointing to Earth. Maybe look at pictures from the Sentinel 1, 2, 3, 5 satellites and get a bit of inspiration from those?

**Comment by Fernerkundung** [comment]
> none of the Sentinels has a parabolic antenna pointing to Earth

I think it is fine this way. The symbol clearly communicates the concept "satellite". It is a logo after all that conveys a message - technical accuracy is not that important.

If we would want to be pedantic we would also need to either change the swath depiction to be TopSAR (for S1) or change the angle to be consistent with an ascending orbit (for S2). ;)

> swath a bit narrower and in a color that stands out more 
On second look this is a +1 from me. If we include it into the Readme the background would be white all the time.

**Comment by yepremyana** [comment]
I see what you guys mean about the swath @Fernerkundung @j08lue , I attached two images here based on both of your feedback, let me know what you think of the pixelated design!

image

image

**Comment by Fernerkundung** [comment]
The pixelation is a nice idea to convey the message of converting the world to pixels. If I look at it in a smaller version (i.e. logo size) the pixelation does not work really well.

I am a fan of your first approach - preferably with a change to the swath color. Or alternatively without the swath and a bigger satellite.

In any way: Thank you again for contributing to this project. A PR for a logo design took all of us by suprise (in a positive way). :+1:

**Comment by yepremyana** [comment]
@Fernerkundung I provided a hybrid of the pixel design and the original swath, I also added different color examples, so please let me know which color you like the best!

Yellow
image

Tangerine
image

orange
image

Pink
image

Navy
image

Purple
image

Lime
image

Transparent Blue
image

Transparent Navy
image

Transparent Red
image

**Comment by j08lue** [comment]
Nice iterations here, thanks @yepremyana! My 2ct:
1. Nice idea, merging pixel and swath, but I am unsure, too, how well it works in small format
1. Color: Yellow looks nice! How about picking the Copernicus logo yellow? https://www.eea.europa.eu/about-us/who/copernicus-1/copernicus-logo/image_view_fullscreen Something like `#FBC819`

So, two versions, one with the first swath and one with the pixel-swath combination, with the Copernicus yellow, then we could pick one of those? 😄

**Comment by j08lue** [comment]
@yepremyana and @Fernerkundung do you want to wrap this up and merge?

I think this was an awesome contribution, @yepremyana. I think the latest design pixel+swath was great and we could just use it as-is, just with Copernicus yellow (see hex code [above](https://github.com/sentinelsat/sentinelsat/pull/319#issuecomment-554034513)).

What do you think, @Fernerkundung? And would you be up for one or two last iterations, @yepremyana?

**Comment by Fernerkundung** [comment]
I'm all for it. 👍 

...and sorry again for being so picky @yepremyana ;)

**Comment by willemarcel** [comment]
It's very nice!! :100:

**Comment by joooeey** [comment]
> We don't have to be extremely accurate about this, but none of the Sentinels has a parabolic antenna pointing to Earth. Maybe look at pictures from the Sentinel 1, 2, 3, 5 satellites and get a bit of inspiration from those?

Since this PR is still open, I'll add my two cents. It would be pretty easy to replace the parabolic antenna by something that looks like the sensor of Sentinel-1.

**Comment by j08lue** [comment]
> It would be pretty easy to replace the parabolic antenna by something that looks like the sensor of Sentinel-1

Contributions are very welcome, @joooeey! 😉

**Comment by j08lue** [comment]
Closing as stale - the issue is still open, though. 😄

**Pull request closed without merging**
