### PR TITLE
Make exceptions more specific

### LINKED ISSUE #131: Make exceptions more specific
I first suggested this change in #108.

I would split `SentinelAPIError` into a couple of more specific ones:

  - `SentinelAPIError`: for relaying API responses that return an exception, e.g. for invalid query parameters. The response is expected to contain the `cause-message` in that case (as in #107).
  - `UnauthorizedError`: for cases where invalid credentials were provided or when the server does not accept them yet for whatever reason (a common issue for new users, I think).
  - `ServerError`: for cases when the server is unreachable, under maintenance or the response is just unparsable garbage.

This would enable different error cases to be caught more elegantly. E.g. you probably just want to retry your query after some delay in case of `ServerError`.

### PR DESCRIPTION
**Pull request by dwlsalmeida**
This commit splits SentinelAPIError into more specific exceptions,
such as UnauthorizedError and ServerError

This is WIP so more tests can be added if needed.

Closes #131

### CODE REVIEW

**Comment by valgur** [comment]
Looks very good at first glance! I'll take a closer look later today or tomorrow.

**Comment by Fernerkundung** [comment]
@valgur Any chance you found time to look more closely into this PR?

**Comment by valgur** [comment]
Sorry for the delay. I intended to take a closer look today, finally, but got sidetracked with fixing unit test regressions (when running without the recorded responses), which resulted in #283.
I hope to get around to properly reviewing this issue tomorrow.

**Comment by Fernerkundung** [comment]
Don't stress it. I just wanted to ask if you still wanted to review this or if someone else should look over this (if they have the time).

**Comment by Fernerkundung** [comment]
Closed - superseded by #285.

**Pull request closed without merging**
