### PR TITLE
Add pypy to TravisCI build environments

### PR DESCRIPTION
**Pull request by valgur**
Just curious to see whether `sentinelsat` works on pypy as well. It should not affect our build time since all builds are run in parallel.

### CODE REVIEW

**Comment by valgur** [comment]
The result is: no, it does not work. Pypy does not support numpy, so pandas will not work.

**Comment by Fernerkundung** [comment]
> Pypy does not support numpy, so pandas will not run

Which is only a dependency for `to_(geo)dataframe` and no one would try to use those when they can't install `pandas` in the first place.

I'd say we can say it works on Pypy, bar this small convenience function.

**Comment by j08lue** [comment]
I don't know whether you would like to spend more time on this. 

But if you do, could we mark that test somehow to only run when `pandas` is installed? It is a conditional import anyways.

**Comment by Fernerkundung** [comment]
Great to know @valgur! That's something we can mention in the docs and point to this closed PR should someone be inclined to use `sentinelsat` with PyPy.

**Pull request closed without merging**
