### PR TITLE
Wait for triggering to finish. Solves #338.

### PR DESCRIPTION
**Pull request by gbaier**
This PR should solve #338 by waiting for the triggering thread to finish.

### CODE REVIEW

**Comment by Fernerkundung** [comment]
Thank you for the quick fix @gbaier!

Can you confirm this works for your example @j08lue? I'd like to get this merged ASAP, since it is a rather critical fix.

**Comment by j08lue** [comment]
I'll test.

**Comment by Fernerkundung** [comment]
Any update from your side @j08lue?

**Comment by j08lue** [comment]
Let's merge this then. I did not have time to test, because I changed my code to trigger/download single products with the `api.download` function, which I was not able to get to work reliably either, so I dug around DIASes for data instead. This LTA is really a party killer. Anyways - merging now.

**Comment by Fernerkundung** [comment]
> This LTA is really a party killer.

If only there was a standardized way for them to provide a metadata catalogue of these spatio-temporal assets...

Oh wait - there is! https://github.com/radiantearth/stac-spec

**Pull request merged**
