### PR TITLE
Add FAQ

### PR DESCRIPTION
**Pull request by martinber**
Hi, I think that a FAQ could be useful, because I was stuck with authentication issues and the answer was on a closed issue (it takes a few days until you can use a new account on apihub).

I don't know if you agree, I looked at some closed issues looking for more problems that people had:

- #178: Query returns 0 results because of time interval (I made that mistake too).
- #178: User asks for something to view the images.
- #73: Authentication issues because of slow account creation on apihub.
- #67 and  #80: 500 time out because of server issues.

So I made a FAQ on README.md with those problems. Keep in mind that maybe I should copy it to the readthedocs documentation, also I'm not a native english speaker so I could have made some mistakes.

Thank you for this useful tool.

### CODE REVIEW

**Comment by j08lue** [comment]
Personally, I hardly ever consult FAQs because they often are formatted in a way that makes it hard to quickly find the problem I have. We could also raise and answer these issues on Stackoverflow and point to that in the docs. That would also make them rank high on Google.

**Comment by Fernerkundung** [comment]
I think in this context it would be more suitable to call them "Known Errors" or "Common Problems" instead of "Frequently Asked Questions".

However, I don't think the Readme is the correct place for this. I'd say these are better listed either:

In the docs:
- pro: works offline and online, can be build by the user
- con: hard to link to Github issues

In the wiki:
- pro: easy to link to issues and PRs
- con: not available offline

If you move this list to either of those locations I'll add my +1, because good documentation matters.

**Comment by martinber** [comment]
There I moved everything to the docs and changed the title to "Common problems". I don't think that the wiki is a good idea because personally I always forget to look there unless there is a link to the wiki on the docs.

**Comment by j08lue** [comment]
> "Known Errors" or "Common Problems"

I kinda like "Known Errors" better, because I don't know how common these problems are - and we don't want to give the (wrong) impression that the library is hard to use. 😄

**Comment by Fernerkundung** [comment]
I've changed the name and merged the documentation of known errors into the master branch.

Thank you for this PR @martinber!

**Pull request merged**
