### PR TITLE
LTA handling improvements

### PR DESCRIPTION
**Pull request by valgur**
- Converted `trigger_offline_retrieval()` into a public method.
- `trigger_offline_retrieval()` now returns True/False depending on whether the product was triggered or is already online and raises an exception in all other cases.
- renamed `SentinelAPILTAError` to `LTAError`, added `LTATriggered` exception.
- `download()` and `get_stream()` now raise `LTATriggered` exception if the product is offline.
- made `get_stream()` more flexible.

### CODE REVIEW

**Comment by valgur** [comment]
This is mostly related to the problems described in #400. @daniel-j-h does this cover all of them or did I miss anything?

**Comment by valgur** [comment]
This is mostly related to the problems described in #400. @daniel-j-h does this cover all of them or did I miss anything?

**Review by j08lue — APPROVED** [review]
Cool. LTA just became an even more prominent part of SciHub distribution, so this improvement of interacting with it will certainly come in handy.

**Review by j08lue — APPROVED** [review]

**Comment by daniel-j-h** [comment]
Awesome to see these improvements!! :bow: 

> Cool. LTA just became an even more prominent part of SciHub distribution, so this improvement of interacting with it will certainly come in handy.

Care to elaborate what you mean by this? :thinking:

**Comment by valgur** [comment]
@daniel-j-h There does not appear to have been any announcements about this, but the online retention period was recently reduced from 12 months to just 30 days: #466.

**Comment by Morteza-Khazaei** [comment]
Hi Valgur, I want to download sentinel-2 products from sci-hub with Sentinelsat version 1.0, But for offline products nothing is not change! and no image not be online after get the exception. I tried it in couple of days, but I didn't get result. Please guide me how can download offline products after triggered thems?


Downloading S2A_MSIL1C_20200131T073131_N0208_R049_T39SUB_20200131T085725.SAFE...
Traceback (most recent call last):
  File "download_s2.py", line 258, in <module>
    main(username='****', password='****', minsize=100.,
  File "download_s2.py", line 250, in main
    zip_files = download(products, output_dir='%s/%s' % (output_dir, tile))
  File "download_s2.py", line 172, in download
    scihub_api.download(uuid, output_dir)
  File "/usr/local/lib/python3.8/site-packages/sentinelsat/sentinel.py", line 525, in download
    raise LTATriggered(id)
sentinelsat.exceptions.LTATriggered: Product 53225f54-0f91-46db-af84-48bb38d15cd1 is not online. Triggered retrieval from the Long Term Archive.

**Comment by j08lue** [comment]
@Morteza-Khazaei please raise a new issue for this. 😉

**Comment by valgur** [comment]
Thanks for reporting this @Morteza-Khazaei! That's a serious bug and regression in sentinelsat. I'll release a fix asap.

**Comment by valgur** [comment]
@Morteza-Khazaei There's a version 1.0.1 with the LTA triggering fixed now available.

**Comment by Morteza-Khazaei** [comment]
Dear Valgur,

Just to keep you posted. The new sentinelsat version 1.0.1 works well only
for the first offline image, that  I put in the loop, but the rest of the
images in the list are not being online. I appreciate it if you help me to
solve this issue.

Cheers,

Morteza

**Comment by valgur** [comment]
That sounds like a bug, indeed. Thanks for letting me know. I created an issue - #487. Also, please create a new issue for problems like this and the previous one in the future - comments under closed issues are extremely easy to miss.

**Pull request merged**
