### PR TITLE
Improve handling of offline products

### PR DESCRIPTION
**Pull request by avalentino**
Never try to trigger LTA retrieval if products are online.

### CODE REVIEW

**Comment by valgur** [comment]
Using `is_online = not self.trigger_offline_retrieval(id)` instead of `is_online = self.is_online(id)` is very deliberate. The `Online` property of products has unfortunately not been 100% reliable and testing with a `trigger_offline_retrieval()` is a foolproof way to get the true status of the product. It's an extra query but is negligible considering the typical download size.

**Comment by avalentino** [comment]
> Using is_online = not self.trigger_offline_retrieval(id) instead of is_online = self.is_online(id) is very deliberate. The Online property of products has unfortunately not been 100% reliable and testing with a trigger_offline_retrieval() is a foolproof way to get the true status of the product. It's an extra query but is negligible considering the typical download size.

The problem is that I often get the following error message

```
User quota exceeded: ExpectedException : User '****' offline products retrieval quota exceeded (20 fetches max)  trying to fetch product S1A_S3_GRDH_1SDV_20201214T152857_20201214T152916_035683_042CC9_BDDA (131284702 bytes compressed)
```

even in the case most of the requested products are online and few of the are offline.
My feeling (not 100% sure) is that the use of `self.trigger_offline_retrieval(id)` seems to increase in any case the count of retrieval attempts even if products are actually online.

Do you think there could be some kind of alternative strategy?

**Comment by j08lue** [comment]
> My feeling (not 100% sure) is that the use of `self.trigger_offline_retrieval(id)` seems to increase in any case the count of retrieval attempts even if products are actually online.

Geez, they are not making this easy! Would you perhaps ask EO Support, whether these status requests indeed count against the quota? I guess this is happening in some kind of API gateway (I hope!), but might still be something they can configure?

Otherwise I would too advocate for going back to the old way of relying on the `Online` status being correct and failing when it is not.

**Comment by avalentino** [comment]
> Geez, they are not making this easy! Would you perhaps ask EO Support, @avalentino, whether these status requests indeed count against the quota? I guess this is happening in some kind of API gateway (I hope!), but might still be something they can configure?

Unfortunately this overlaps with #493 so it id hard to provide a reproducible example to the support team.
I will try in any case.

**Comment by j08lue** [comment]
I also saw the issue with tons of 403 errors (too many requests) from `api.download_all` and the change in this branch got rid of them. Curiously, I got these issues only when downloading Sentinel-1 SLC products (and not even LTA ones).

I propose to merge this and open an issue to go back to calling `trigger_offline_retrieval` to reliably get the online status. What do you think, @valgur?

**Comment by valgur** [comment]
I agree, let's merge this change. Will have to think of a solution for dealing with incorrect Online status in OData, but that's a much-much less severe issue and can be ignored in the short term.

**Pull request merged**
