### PR TITLE
issue #183 : remove hard coded product type list from cli

### PR DESCRIPTION
**Pull request by lenniezelk**

### CODE REVIEW

**Comment by lenniezelk** [comment]
@j08lue @Fernerkundung any feedback on this?

**Comment by lenniezelk** [comment]
on it @j08lue

**Comment by lenniezelk** [comment]
i added a link to list of product types. Not sure if its complete though @j08lue

**Comment by Fernerkundung** [comment]
Thank you for this PR @lenniezelk.

**Pull request merged**
