### PR TITLE
Avoid UnboundLocalError with area wkt in CLI

### LINKED ISSUE #155: Error when --geometry not set
An exception is thrown when `--geometry` is not included in the CLI arguments.

```
File "cli.py", line 138, in cli
    products = api.query(area=wkt, date=(start, end),
UnboundLocalError: local variable 'wkt' referenced before assignment
```

### PR DESCRIPTION
**Pull request by j08lue**
Fixes #155

### CODE REVIEW

**Comment by Fernerkundung** [comment]
There seem to be some leftover commits from #162. Do you mind if I squash them with the merge?

**Comment by j08lue** [comment]
> Do you mind if I squash them with the merge?

Please do, and tell me how you do that. 😄

**Comment by j08lue** [comment]
ahh - the "Squash and merge" option on the drop-down menue on GitHub?

**Comment by Fernerkundung** [comment]
Yep, that one.

Personally I find that a lot easier than asking people to rebase. 😉

**Pull request merged**
